<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Approve' => '',
    'Approve post' => '',
    'Do you really want to approve this post?' => '',
    '<strong>Confirm</strong> post deletion' => '<strong>Подтвердите</strong> удаление сообщения',
    '<strong>Confirm</strong> report deletion' => '<strong>Подтвердите</strong> удаление репорта',
    'Cancel' => 'Отменить',
    'Content' => 'Содержание',
    'Delete' => 'Удалить',
    'Delete post' => 'Удалить сообщение',
    'Do you really want to delete this post? All likes and comments will be lost!' => 'Вы действительно хотите удалить это сообщение? Все лайки и комментарии и будут потеряны!',
    'Reason' => 'Причина',
    'Reporter' => 'Репорт',
    'There are no reported posts.' => 'Здесь не зарегистрировано ни одного сообщения.',
];
